Add materialized view support for BigQuery and Snowflake
dataform-co/dataform pull request #1302
Opened 2022-01-26 09:45 UTC by canberkkoparal

#1190 and #710

2022-01-26 11:39 UTC, BenBirt commented
This looks great, thanks!

I know you won't be able to see them, but the failing tests are:

```
@dataform/integration/bigquery > run > project e2e                       FAILED

    AssertionError: expected 19 to deeply equal 18
        at Test.fn (tests/integration/bigquery.spec.ts:44:45)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at testing/test.ts:74:15
        at Test.run (testing/test.ts:63:9)
        at runTestOrSuite (testing/suite.ts:80:7)
        at async Promise.all (index 0)
        at Suite.run (testing/suite.ts:89:9)
        at runTestOrSuite (testing/suite.ts:80:7)
        at async Promise.all (index 0)


    Expected:

    18

    Actual:

    19

    Overall diff (expected -, actual +):

    18+   19
```

```
@dataform/integration/snowflake > run                                    FAILED

    AssertionError: expected 21 to deeply equal 20
        at Test.fn (tests/integration/snowflake.spec.ts:47:43)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at testing/test.ts:74:15
        at Test.run (testing/test.ts:63:9)
        at runTestOrSuite (testing/suite.ts:80:7)
        at Suite.run (testing/suite.ts:92:11)
        at async Promise.all (index 0)
        at Function.run (testing/runner.ts:57:7)


    Expected:

    20

    Actual:

    21

    Overall diff (expected -, actual +):

    20+   21
```

2022-01-26 11:39 UTC, BenBirt requested changes

2022-01-26 11:39 UTC, BenBirt commented on core/table.ts
> +   * Only allowed when using Snowflake or BigQuery warehouse.
nit: "Only valid when using Snowflake or BigQuery."

2022-01-26 11:39 UTC, BenBirt commented on core/table.ts
> +   * Only allowed when the table type is `view`.
nit: s/allowed/valid/

2022-01-26 11:39 UTC, BenBirt commented on examples/common_v2/definitions/example_materialized_view.sqlx
> +config {type: "view", materialized: true}
supernit: git complaining that this and other new files don't have trailing newlines

2022-01-27 10:39 UTC, astorrs commented
@canberkkoparal This is amazing! 

For BigQuery it would be good to expose setting the `enableRefresh` and `refreshIntervalMs` options to allow for finer control (https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#materializedviewdefinition). 

Otherwise an ALTER MATERIALIZED VIEW statement would have to be done in a post_operation in Dataform to adjust https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#materialized_view_set_options_list). 

Any opinion on extending the config @BenBirt @lewish ?

As far as I’m aware Snowflake doesn’t currently allow you to tune the refresh rate in the same way.

2022-01-27 10:44 UTC, BenBirt commented
@astorrs I'm all up for extending configuration options further, but: it seems that the default for `enableRefresh` is `true`; why would a user ever want to disable it (for Dataform-managed MVs, at least)? (this just sounds like `type: "table"` to me)

Allowing configurability of `refreshIntervalMs` makes sense. @canberkkoparal WDYT?

2022-01-27 11:09 UTC, astorrs commented
@BenBirt you're probably right on the `enableRefresh`; the only time I’ve used it is when you want to trigger a refresh based on some external event and with Dataform driving it’s redundant. 

`refreshIntervalMs` is more important since we run our Dataform jobs more frequently than every 30 mins (which is the default max refresh window) and I want them to be at least that fresh. The unique benefit of materialized views in BQ is the way it seamlessly incorporates data from the streaming buffer into the view in between refreshes.

2022-01-27 11:17 UTC, BenBirt commented
@astorrs just to be clear I'm assuming you mean at *most* that fresh?

2022-01-27 11:19 UTC, BenBirt commented
@astorrs took me a couple of reads but that makes sense, thanks!

Given that BQ DDL only lets us specify this interval in minutes, we'll probably go with something more like `refreshIntervalMins`, but SGTM.

2022-01-27 12:14 UTC, BenBirt approved these changes
Update https://github.com/dataform-co/dataform/blob/master/version.bzl to `1.21.0`? Then I'll publish a new release.

2022-01-27 12:30 UTC, merged