Options
dataform-co/dataform pull request #1332
Opened 2022-04-15 07:47 UTC by stankiewicz

this includes:

require_partition_filter
partition_expiration_days
which are common options to set in partitoned data models.
At this moment it requires additional step (manual gcloud) to patch the table.

this change is not patching/updating the existing tables, it only affect create table DDL.

2022-04-26 11:21 UTC, stankiewicz commented
@canberkkoparal can I have update on this? thanks!

2022-04-26 12:37 UTC, canberkkoparal commented
Implementation LGTM
You should add validity checking [here](https://github.com/dataform-co/dataform/blob/99ba7ace2c79561f85046929ba733f7d915856ae/core/session.ts#L736), throwing an error if target is a view or if there is no partitionBy.
Also can you add compilation tests: both [passing](https://github.com/dataform-co/dataform/blob/99ba7ace2c79561f85046929ba733f7d915856ae/tests/core/core.spec.ts#L569) and [failing](https://github.com/dataform-co/dataform/blob/99ba7ace2c79561f85046929ba733f7d915856ae/tests/core/core.spec.ts#L475)
Finally you can add even more testing by writing [integration](https://github.com/dataform-co/dataform/blob/master/tests/integration/bigquery.spec.ts) and [example](https://github.com/dataform-co/dataform/blob/master/tests/api/examples.spec.ts) tests but those are not critical.

2022-04-28 14:46 UTC, canberkkoparal requested changes

2022-04-28 14:46 UTC, canberkkoparal commented on protos/core.proto
> +
nit: delete extra empty line

2022-05-04 09:39 UTC, stankiewicz commented
I can't merge it (don't have permissions)  - @canberkkoparal @lewish can you merge it?

2022-05-04 09:42 UTC, merged