[#1466] Filter intersection of tags
dataform-co/dataform pull request #1467
Opened 2023-03-11 13:33 UTC by AnOtterGithubUser

Hello,
I added a new flag `--include-all-tags` that works with `--tags` options to get the behavior requested in #1466    
Default flag value is set to false to keep existing behavior unchanged

2024-03-28 10:23 UTC, Ekrekr requested changes
Sorry that this went under the radar for so long! It just needs a sync and a few nits, then we can get this in.

2024-03-28 10:23 UTC, Ekrekr commented on protos/execution.proto
> +  bool include_all_tags = 10;
"include all" is ambiguous in semantic meaning - IMO something like `filterTagsAsIntersection` would be better as it's more explicit.

2024-03-28 10:23 UTC, Ekrekr commented on tests/api/api.spec.ts
> +      expect(actionNames).not.includes("schema.op_d");
This would be better as `expect(actionNames).deep.equals(["schema.op_e", "schema.op_a"]);`

2024-03-28 10:23 UTC, Ekrekr commented on api/commands/prune.ts
> +    // Keep actions wich include every tags in --tag option
```suggestion
    // Select actions which match the intersection of the set of tags.
```

2024-03-28 10:23 UTC, Ekrekr commented on api/commands/prune.ts
> +    // Keep actions with include at least one tag in --tag option
```suggestion
    // Select actions which match the union of the set of tags.
```

2025-05-14 11:31 UTC, zsomborkincses commented
It would be great if this feature was added!

2026-07-13 16:14 UTC, apilaskowski commented
Closing, as new PR was proposed base on this, and no movement in either.

2026-07-13 16:14 UTC, closed without merging