Move concurrency and action retries from project config proto to the CLI
dataform-co/dataform pull request #1585
Opened 2023-11-22 14:45 UTC by Ekrekr

As they are not valid options for `workflow_settings.yaml`

2023-11-22 15:12 UTC, canberkkoparal requested changes
LGTM, but you also need to update the cli test

2023-11-22 15:12 UTC, Ekrekr commented on tests/api/api.spec.ts
> +              actionRetryLimit: 1,
This doesn't do what I thought it did, will think about the fix

2023-11-22 15:50 UTC, Ekrekr commented on tests/api/api.spec.ts
> +              actionRetryLimit: 1,
Fixed, the option just needed to be passed into the runner instead.

2023-11-24 10:36 UTC, canberkkoparal approved these changes

2023-11-24 12:17 UTC, merged