Restore ability to run unit tests
dataform-co/dataform pull request #1824
Opened 2024-09-02 21:45 UTC by bmagyarkuti

Prior to release `3.0.1`, it was possible to unit tests views. For example:
```js
test("test a view")
  .dataset("example_view")
  .input(
    "sample_data",
    "select 'hi' as col1, 1 as col2, 3.5 as col3, true as col4, date '2020-07-23' as col5"
  )
  .expect(
    "select 'hi' as col1, 1 as col2, 3.5 as col3, true as col4, date '2020-07-23' as col5"
  );
```

Such a unit test always fails after `3.0.1` (including `3.0.2`). It produces the following error message:
`Dataset sample_data could not be found`. This happens regardless of whether such a dataset has been defined.

This commit re-introduces the ability to unit test views.

I'd like to nominate @Ekrekr as reviewer.

2024-09-03 06:21 UTC, lveraszto commented
+1

2024-09-03 09:21 UTC, Ekrekr requested changes
Thanks for the fix!

2024-09-03 09:21 UTC, Ekrekr commented on core/actions/test.ts
> +import * as view from "df/core/actions/view";
```suggestion
import {View} from "df/core/actions/view";
```

2024-09-03 09:21 UTC, Ekrekr commented on tests/integration/bigquery_project/definitions/test.js
> +  );
+newline at end of file

2024-09-03 17:42 UTC, bmagyarkuti commented
@Ekrekr I've incorporated both your suggested changes. Is there anything else I need to do before this can be merged?

2024-09-05 15:07 UTC, Ekrekr commented
Thanks - I've run the tests and they're all good, I just need you to sign the CLA before I can merge.

2024-09-05 15:19 UTC, barna-emarsys commented
@Ekrekr, when I accepted your suggested changes, you became a co-author on that commit, and your @gmail address seems to be missing a CLA, so it seems you now need to sign the CLA. Sorry about this, maybe it was a bad idea to use Github's built-in "accept changes" functionality.

2024-09-05 17:08 UTC, Ekrekr approved these changes

2024-09-05 17:09 UTC, Ekrekr commented
Huh weird, I see that too, but it also shows as me having already signed it when I follow the link. Will just merge through it!

2024-09-05 17:09 UTC, merged